---
- name: Ensure group "nginx_user" exists
  group:
    name: "{{ nginx_user }}"
    state: present

- name: Ensure user "nginx_user" exists
  user:
    name: "{{ nginx_user }}"
    state: present
    groups: "{{ nginx_user }}"
    create_home: no
    append: yes

- name: "Create folder {{ nginx_folder }}"
  file:
    path: "{{ nginx_folder }}"
    recurse: yes
    state: directory
    owner: {{ nginx_user }}
    group: {{ nginx_user }}
    mode: 0775

- name: Edit nginx conf file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0775

- name: Ensure nginx is restarted
  service:
    name: "{{ nginx_daemon }}"
    state: "restarted"
    enabled: "true"