---
- name: Install dependencies and ensure they're here
  apt: 
    name: "{{ item }}"
    update_cache: true
    state: latest
  with_items:
    - curl
  tags: packages

- name: Install nginx
  apt: 
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - nginx
  tags: packages

- name: "Create log folder {{ web_folder }}"
  file:
    path: "/usr/share/nginx/logs"
    recurse: yes
    state: directory
    owner: "{{ webserver_user }}"
    group: "{{ webserver_user }}"
    mode: 0775  

- name: Ensure nginx is restarted
  service:
    name: "{{ nginx_daemon }}"
    state: "started"
    enabled: "true"